name: 'Deployment to Microsoft Azure'
on:
  workflow_call:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

jobs:
  deployment-job:
    name: 'Deplyoment to Microsoft Azure'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.0.0

      - name: 'Azure Container Registry Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build the docker image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY_LOGIN_SERVER }}/pull-request-${{ env.PR_NUMBER }}:latest

      - name: Deploy to Microsoft Azure
        run: echo Deploying succed


