name: 'Deployment to Microsoft Azure'

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      environment:
        required: true
        type: string
        default: other
    secrets:
      server:
        required: true
      username:
        required: true
      password:
        required: true

jobs:
  deployment-job:
    name: 'Deplyoment to Microsoft Azure'
    runs-on: ubuntu-latest
    steps:
      - name: Print values
        run: echo "${{ inputs.environment }}"
      # - name: Checkout the code
      #   uses: actions/checkout@v3.0.0

      # - name: 'Azure Container Registry Login'
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.server }}
      #     username: ${{ secrets.username }}
      #     password: ${{ secrets.password }}

      # - name: Build the docker image and push it to ACR
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ secrets.server }}/pull-request-${{ inputs.pr-number }}:latest

      # - name: Deploy to Microsoft Azure
      #   run: echo "Docker image and Pull request ${{ inputs.pr-number }} deployed."


