name: 'CI & CD'
on:
  push:
    branches:
      - main

jobs:
  testing:
    name: 'Executing tests'
    runs-on: ubuntu-latest
    environment: stagging
    container:
      image: ruby:3.0.4
    services:
      database:
        image: postgres:latest
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bundle install

      - name: Run migrations
        run: rails db:create RAILS_ENV=test

      - name: Run specs
        run: rspec spec
