name: 'CI & CD - Production'
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  testing:
    name: Running Testing Workflow
    uses: ./.github/workflows/testing-workflow.yml

  deployment-ms-azure:
    name: Deploy to Microsft Azure
    uses: ./.github/workflows/microsoft-azure.yml
    with:
      environment: production
    secrets:
      server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}
    needs: testing
