name: 'CI & CD'
on:
  push:
    branches:
      - main

jobs:
  testing:
    name: 'Executing tests'
    runs-on: ubuntu-latest
    environment: stagging
    container:
      image: ruby:3.0.4
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bundle install

      # - name: Run migrations
      #   run: rails db:create db:migrate

      # - name: Run specs
      #   run: rspec spec
