name: 'CI & CD - Pull Request'
on:
  pull_request:
    types: [opened]

  workflow_dispatch:

jobs:
  testing:
    name: Running Testing Workflow
    uses: ./.github/workflows/testing-workflow.yml

  deployment:
    name: Deploy to Microsft Azure
    uses: ./.github/workflows/azure-deployment.yml
