name: 'CI & CD - Pull Request'
on:
  pull_request:
  workflow_dispatch:

env:
  MICROSOFT_AZURE_NAME: rails-to-azure-services

jobs:
  testing:
    name: Running Testing Workflow
    uses: ./.github/workflows/testing-workflow.yml

  deployment:
    name: Deploy to Microsft Azure
    uses: ./.github/workflows/azure-deployment.yml
    needs: testing

  deployment-azure:
    runs-on: ubuntu-latest
    needs: deployment
    steps:
      - name: Deploy to Microsof Azure Container Registry
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.MICROSOFT_AZURE_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
