name: 'CI & CD - Stagging'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  testing:
    name: Running Testing Workflow
    uses: ./.github/workflows/testing-workflow.yml

  deployment:
    name: Deploy to Microsft Azure
    uses: ./.github/workflows/microsoft-azure.yml
    with:
      environment: stagging
    secrets:
      server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}
    needs: testing
