name: 'CI & CD - Production'
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  testing:
    name: Running Testing Workflow
    uses: ./github/workflows/testing-workflow.yml

  deployment:
    name: Deploy to Microsft Azure
    uses: ./.github/workflows/azure-deployment.yml
    needs: testing
