name: 'Deployment to Microsoft Azure'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: other
      pr-name:
        required: true
        type: string
      pr-number:
        required: true
        type: string
    secrets:
      server:
        required: true
      username:
        required: true
      password:
        required: true

jobs:
  authentication-ms-azure:
    name: 'Authentication with Microsoft Azure'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.0.0

      - name: 'Azure Container Registry Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

  deployment-ms-azure-pull-request:
    if: ${{ inputs.environment == 'pull_request' }}
    name: Deployment from Pull Request environment
    runs-on: ubuntu-latest
    needs: authentication-ms-azure
    steps:
      - name: Build the docker image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.server }}/pull-request-${{ inputs.pr-number }}-${{ inputs.pr-name }}:latest

  deployment-ms-azure-stagging:
    if: ${{ inputs.environment == 'stagging' }}
    name: Deployment from Stagging environment
    runs-on: ubuntu-latest
    needs: authentication-ms-azure
    steps:
      - name: Build the docker image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.server }}/pull-request-stagging:latest

  deployment-ms-azure-production:
    if: ${{ inputs.environment  == 'production' }}
    name: Deployment from Production environment
    runs-on: ubuntu-latest
    needs: authentication-ms-azure
    steps:
      - name: Build the docker image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.server }}/pull-request-production:latest
