name: 'Deployment to Microsoft Azure'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: other
      pr-name:
        type: string
      pr-number:
        type: string
    secrets:
      server:
        required: true
      username:
        required: true
      password:
        required: true

jobs:
  # ========== Pull Request Configuration ===========
  deployment-ms-azure-pull-request:
    if: ${{ inputs.environment == 'pull_request' }}
    name: Pull Request - Deployment
    runs-on: ubuntu-latest
    environment: pull-request/${{ inputs.pr-number }}-${{ inputs.pr-name }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.0.0

      - name: 'Azure Container Registry Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build the docker image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.server }}/pull-request-${{ inputs.pr-number }}-${{ inputs.pr-name }}:latest

  # ========== Stagging Configuration ===========
  deployment-ms-azure-stagging:
    if: ${{ inputs.environment == 'stagging' }}
    name: Stagging - Deployment
    runs-on: ubuntu-latest
    environment: stagging
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.0.0

      - name: 'Azure Container Registry Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build the docker image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.server }}/stagging:latest

  # ========== Production Configuration ===========
  deployment-ms-azure-production:
    if: ${{ inputs.environment  == 'production' }}
    name: Production - Deployment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.0.0

      - name: 'Azure Container Registry Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build the docker image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.server }}/production:latest
